spring:
  datasource:
    url: jdbc:mysql://todolist.cvzpkqdwzwik.ap-northeast-2.rds.amazonaws.com:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jun
    password: 12341234
server:
  port: 8082
